import { FieldConfig, FieldVisibilitySettings, OptionalFieldKey } from "../types";

export const DEFAULT_FIELD_VISIBILITY: FieldVisibilitySettings = {
  org_id: true,
  client_id: true,
  created_date: true,
  expiry_date: true,
  account: true,
  project: true,
  environment: true,
  last_used_date: true,
  status: true,
  ip_restrictions: true,
  portal_url: true,
  creator_contact: true,
  purpose: true,
};

export const FIELD_CONFIGS: FieldConfig[] = [
  {
    key: "org_id",
    label: "Organization ID (Org ID)",
    description: "Provider organization ID or Team ID (masked)",
    category: "General",
    type: "text",
    placeholder: "e.g., org_89104fa2089b, org-prod-us1",
  },
  {
    key: "client_id",
    label: "Client ID (App ID)",
    description: "OAuth / API Provider Client ID or App ID (masked)",
    category: "General",
    type: "text",
    placeholder: "e.g., client_4901bcf8910a, app_9018471b",
  },
  {
    key: "environment",
    label: "Environment",
    description: "Deployment target (e.g., Homelab, Prod, Dev, Staging)",
    category: "General",
    type: "select",
    options: ["Homelab", "Prod", "Dev", "Staging", "Testing", "DMZ"],
    placeholder: "Select or type environment",
  },
  {
    key: "status",
    label: "Status",
    description: "Operational status of the key (Active, Revoked, Paused)",
    category: "Security & Access",
    type: "select",
    options: ["Active", "Revoked", "Paused"],
    placeholder: "Active",
  },
  {
    key: "expiry_date",
    label: "Expiry Date",
    description: "Expiration deadline for automated lifecycle tracking",
    category: "Dates & Lifecycle",
    type: "date",
    placeholder: "YYYY-MM-DD",
  },
  {
    key: "created_date",
    label: "Created Date",
    description: "Timestamp when the key was provisioned",
    category: "Dates & Lifecycle",
    type: "date",
    placeholder: "YYYY-MM-DD",
  },
  {
    key: "last_used_date",
    label: "Last Used Date",
    description: "Timestamp of most recent service communication",
    category: "Dates & Lifecycle",
    type: "date",
    placeholder: "YYYY-MM-DD",
  },
  {
    key: "project",
    label: "Project / Service",
    description: "Associated homelab project, cluster, or container service",
    category: "General",
    type: "text",
    placeholder: "e.g., Home Automation, Media Stack, K3s Cluster",
  },
  {
    key: "account",
    label: "Account / User",
    description: "Service account, IAM username, or email linked to this token",
    category: "General",
    type: "text",
    placeholder: "e.g., root@pam, sysadmin@local, ha_bot",
  },
  {
    key: "ip_restrictions",
    label: "IP Restrictions / CIDR",
    description: "Allowed client IP addresses, subnet CIDR, or Tailnet ACLs",
    category: "Security & Access",
    type: "text",
    placeholder: "e.g., 192.168.1.0/24, 100.64.0.0/10",
  },
  {
    key: "portal_url",
    label: "Portal URL",
    description: "Direct management console or API dashboard URL",
    category: "General",
    type: "url",
    placeholder: "https://pve.internal:8006 or https://dash.cloudflare.com",
  },
  {
    key: "creator_contact",
    label: "Creator / Contact",
    description: "Email or handle of the person/script who generated the key",
    category: "Contact & Notes",
    type: "text",
    placeholder: "admin@homelab.local or #devops-infra",
  },
  {
    key: "purpose",
    label: "Purpose & Notes",
    description: "Description of capabilities, permissions, or scope notes",
    category: "Contact & Notes",
    type: "textarea",
    placeholder: "Describe the scope, permissions, and intended usage...",
  },
];

export const VISIBILITY_PRESETS: Record<string, { label: string; description: string; settings: FieldVisibilitySettings }> = {
  all: {
    label: "Show All Fields",
    description: "Full visibility for comprehensive homelab documentation",
    settings: {
      org_id: true,
      client_id: true,
      created_date: true,
      expiry_date: true,
      account: true,
      project: true,
      environment: true,
      last_used_date: true,
      status: true,
      ip_restrictions: true,
      portal_url: true,
      creator_contact: true,
      purpose: true,
    },
  },
  minimal: {
    label: "Minimalist",
    description: "High-density view with only Environment, Status, and Expiry",
    settings: {
      org_id: false,
      client_id: false,
      created_date: false,
      expiry_date: true,
      account: false,
      project: false,
      environment: true,
      last_used_date: false,
      status: true,
      ip_restrictions: false,
      portal_url: false,
      creator_contact: false,
      purpose: false,
    },
  },
  security: {
    label: "Security Audit",
    description: "Focused on IP restrictions, Expiry, Status, and Owner",
    settings: {
      org_id: true,
      client_id: true,
      created_date: true,
      expiry_date: true,
      account: true,
      project: false,
      environment: true,
      last_used_date: true,
      status: true,
      ip_restrictions: true,
      portal_url: false,
      creator_contact: true,
      purpose: true,
    },
  },
  homelab: {
    label: "Standard Homelab",
    description: "Balanced selection for homelab services and dashboard links",
    settings: {
      org_id: true,
      client_id: true,
      created_date: false,
      expiry_date: true,
      account: true,
      project: true,
      environment: true,
      last_used_date: true,
      status: true,
      ip_restrictions: false,
      portal_url: true,
      creator_contact: false,
      purpose: true,
    },
  },
};
